import ExcelJS from 'exceljs';
import { jsPDF } from 'jspdf';
import { writeCsv } from '../../csv/csvCodec';
import { sanitizeCsvCell } from '../../csv/sanitize';
import { triggerDownload } from '../../csv/streamCsvExport';
import { fromMoney, type Money } from '../money';
import { taxTotalPaise, type GstAmounts, type MonthlyGstCalculation, type NormalizedGstDocument, type NormalizedGstRateRow, type NormalizedHsnRow } from './types';

declare const __APP_VERSION__: string;

export const GST_WORKING_DISCLAIMER = 'Books-based GST working generated by BusinessVault for review by the taxpayer and tax professional. Purchase-side ITC is subject to eligibility review and reconciliation with GST Portal data. This workbook is not proof of filing and is not an official GST Portal statement or GSTN upload file.';
export const GST_WORKBOOK_SHEETS = ['Overview', 'Monthly Summary', 'Sales Register', 'G1 B2B', 'G1 B2CL', 'G1 B2CS', 'G1 Other', 'Sales Notes', 'HSN B2B', 'HSN B2C', 'Documents', 'Purchase Register', 'Purchase Returns', 'Books ITC', 'GSTR3B Working', 'Issues', 'Reconciliation', 'Metadata'] as const;
export const GSTR1_CA_SHEETS = ['GSTR1 Report', 'b2b,sez,de', 'b2cl', 'b2cs', 'cdnr', 'cdnur', 'exp', 'at', 'atadj', 'exemp', 'hsn(b2b)', 'hsn(b2c)', 'itemSummary', 'docs', 'Validation'] as const;
export const PURCHASE_CA_SHEETS = ['Purchase Register', 'b2b', 'b2bur', 'imps', 'impg', 'cdnr', 'cdnur', 'at', 'atadj', 'exemp', 'itcr', 'hsnsum', 'itemSummary', 'Validation'] as const;
type SheetName = typeof GST_WORKBOOK_SHEETS[number];
type Row = Record<string, unknown>;
type Table = { columns: string[]; rows: Row[] };
const AMOUNTS: (keyof GstAmounts)[] = ['taxable_paise', 'igst_paise', 'cgst_paise', 'sgst_paise', 'cess_paise', 'pre_round_total_paise', 'round_off_paise', 'total_paise'];
const LINE_AMOUNTS = AMOUNTS.filter(key => key !== 'total_paise' && key !== 'round_off_paise');
const DOCUMENT_COLUMNS = ['source_entity_type', 'source_entity_id', 'source_entity_version', 'document_type', 'document_number', 'document_date', 'party_id', 'party_name', 'party_gstin', 'recipient_category', 'place_of_supply', 'is_interstate', 'classification', 'effect_sign', 'included', 'exclusion_reason', 'cancelled', 'original_source_entity_id', 'original_document_number', 'original_period_key', 'amendment_kind', 'ecommerce_operator_gstin', 'reverse_charge', 'line_count', ...AMOUNTS];
const RATE_COLUMNS = ['section', 'source_entity_type', 'source_entity_id', 'document_number', 'document_date', 'party_name', 'party_gstin', 'recipient_category', 'document_type', 'reverse_charge', 'original_document_number', 'original_period_key', 'amendment_kind', 'source_line_ids', 'classification', 'tax_rate_bps', 'taxability', 'place_of_supply', 'ecommerce_operator_gstin', ...LINE_AMOUNTS];
const HSN_COLUMNS = ['recipient_group', 'hsn', 'description', 'uqc_code', 'goods_or_service', 'taxability', 'tax_rate_bps', 'quantity_micros', 'source_entity_ids', 'source_line_ids', ...LINE_AMOUNTS];
const MONEY_FORMAT = '#,##0.00;[Red](#,##0.00);"-"';
const EXCEL_MAX_PAISE = 999_999_999_999_999;
// Optional additions also permit presentation of older saved v1 calculations.
type ExportCalculation = MonthlyGstCalculation & {
  savedReportRunId?: string;
  savedStatus?: string;
  b2csAggregates?: Array<Partial<GstAmounts> & { source_entity_ids: string[]; source_line_ids?: string[]; tax_rate_bps: number; place_of_supply: string }>;
};
const SPECIAL_COLUMNS = ['shipping_bill_number', 'shipping_bill_date', 'port_code', 'section_9_5_role', 'section_52_tcs', 'ecommerce_reporting_type'];
const CA_MONEY_COLUMNS = new Set(['Round Off Amount', 'Document Value', 'Invoice Value', 'Taxable Value', 'Integrated Tax Amount', 'Central Tax Amount', 'State/UT Tax Amount', 'Cess Amount', 'Total Value', 'Books Tax', 'Eligible', 'Temporarily Reversed', 'Permanently Reversed', 'Reclaimable', 'Reclaimed', 'Approved Books ITC']);
function isCaMoneyColumn(column: string): boolean { return CA_MONEY_COLUMNS.has(column) || /^(Expected|Export|Variance) (Taxable Value|Integrated Tax Amount|Central Tax Amount|State\/UT Tax Amount|Cess Amount|Approved Books ITC)$/.test(column); }

function money(paise: unknown): string {
  if (typeof paise !== 'number' || !Number.isSafeInteger(paise)) throw new Error('GST export requires safe integer paise');
  // Division near MAX_SAFE_INTEGER can round up before fromMoney floors it.
  if (Math.abs(paise) > EXCEL_MAX_PAISE) {
    const absolute = BigInt(Math.abs(paise));
    return `${paise < 0 ? '-' : ''}${absolute / 100n}.${String(absolute % 100n).padStart(2, '0')}`;
  }
  return fromMoney(paise as Money).replace(/,/g, '');
}

function excelMoney(paise: unknown): number {
  const number = Number(money(paise));
  if (Math.abs(paise as number) > EXCEL_MAX_PAISE || Math.round(number * 100) !== paise) {
    throw new Error('GST XLSX amount cannot preserve paise within Excel 15-digit precision. Download CSV or BusinessVault working JSON for exact values.');
  }
  return number;
}

function selectedResults(results: MonthlyGstCalculation[]): MonthlyGstCalculation[] {
  if (!results.length) throw new Error('Select at least one GST month');
  const first = results[0];
  const periods = new Set<string>();
  for (const result of results) {
    if (result.businessId !== first.businessId || result.gstinSnapshot !== first.gstinSnapshot || result.period.filingFrequency !== first.period.filingFrequency) throw new Error('GST exports require one business registration and filing frequency');
    if (result.period.businessId !== result.businessId || result.period.gstinSnapshot !== result.gstinSnapshot) throw new Error('GST calculation and period registration differ');
    if (result.period.periodType !== 'MONTH' || !/^\d{4}-(0[1-9]|1[0-2])$/.test(result.period.periodKey)) throw new Error('GST exports require monthly calculations');
    if (periods.has(result.period.periodKey)) throw new Error('Duplicate GST period');
    periods.add(result.period.periodKey);
  }
  return [...results].sort((a, b) => a.period.periodKey.localeCompare(b.period.periodKey));
}

function filename(results: MonthlyGstCalculation[], extension: string): string {
  return `BusinessVault-GST-Working-${results[0].period.periodKey}${results.length > 1 ? `-to-${results[results.length - 1].period.periodKey}` : ''}.${extension}`;
}

function caAmounts(row: GstAmounts): Row {
  return {
    'Taxable Value': row.taxable_paise,
    'Integrated Tax Amount': row.igst_paise,
    'Central Tax Amount': row.cgst_paise,
    'State/UT Tax Amount': row.sgst_paise,
    'Cess Amount': row.cess_paise,
  };
}

function caDocumentRow(row: NormalizedGstDocument, documentLabel: string): Row {
  return {
    'GSTIN/UIN': row.party_gstin,
    'Party Name': row.party_name,
    [documentLabel]: row.document_number,
    'Document Date': row.document_date,
    'Document Value': row.total_paise,
    'Round Off Amount': row.round_off_paise,
    'Place Of Supply': row.place_of_supply,
    Classification: row.classification,
    'Reverse Charge': row.reverse_charge ? 'Y' : 'N',
    ...caAmounts(row),
  };
}

function caOutwardCustomerRow(row: NormalizedGstDocument): Row {
  return {
    'Customer GST Number': row.party_gstin,
    'Customer Name': row.party_name,
    'Invoice Number': row.document_number,
    'Invoice Date': row.document_date,
    'Invoice Value': row.total_paise,
    'Round Off Amount': row.round_off_paise,
    'Place Of Supply': row.place_of_supply,
    Classification: row.classification,
    ...caAmounts(row),
  };
}

function caRateRow(row: Pick<NormalizedGstRateRow, 'place_of_supply' | 'classification' | 'tax_rate_bps'> & GstAmounts): Row {
  return {
    'Place Of Supply': row.place_of_supply,
    Classification: row.classification,
    Rate: row.tax_rate_bps / 100,
    ...caAmounts(row),
  };
}

function caHsnRow(row: NormalizedHsnRow): Row {
  return {
    HSN: row.hsn,
    Description: row.description,
    UQC: row.uqc_code,
    'Total Quantity': row.quantity_micros / 1_000_000,
    'Total Value': row.total_paise,
    Rate: row.tax_rate_bps / 100,
    ...caAmounts(row),
  };
}

function paiseSum(rows: Row[], key: string): number {
  return rows.reduce((total, row) => {
    const value = row[key];
    if (typeof value !== 'number' || !Number.isSafeInteger(value)) return total;
    const next = total + value;
    if (!Number.isSafeInteger(next)) throw new Error(`GST CA export ${key} exceeds the safe integer range`);
    return next;
  }, 0);
}

const CA_TAX_COLUMNS = ['Taxable Value', 'Integrated Tax Amount', 'Central Tax Amount', 'State/UT Tax Amount', 'Cess Amount'] as const;
const CA_TAX_KEYS: Array<[typeof CA_TAX_COLUMNS[number], keyof GstAmounts]> = [
  ['Taxable Value', 'taxable_paise'], ['Integrated Tax Amount', 'igst_paise'], ['Central Tax Amount', 'cgst_paise'], ['State/UT Tax Amount', 'sgst_paise'], ['Cess Amount', 'cess_paise'],
];

function sumAmounts(rows: Array<Partial<GstAmounts>>): GstAmounts {
  const total: GstAmounts = { taxable_paise: 0, igst_paise: 0, cgst_paise: 0, sgst_paise: 0, cess_paise: 0, pre_round_total_paise: 0, round_off_paise: 0, total_paise: 0 };
  for (const row of rows) for (const key of AMOUNTS) {
    const value = row[key] ?? 0;
    if (!Number.isSafeInteger(value)) throw new Error('GST CA export requires safe integer paise');
    total[key] += value;
    if (!Number.isSafeInteger(total[key])) throw new Error('GST CA export total exceeds the safe integer range');
  }
  return total;
}

function caControl(control: string, expected: GstAmounts, actual: GstAmounts, expectedDocuments: string[], actualDocuments: string[], expectedParties: string[] | null, actualParties: string[] | null, message: string): Row {
  const documentVariance = actualDocuments.length - expectedDocuments.length;
  const partyVariance = expectedParties === null || actualParties === null ? null : actualParties.length - expectedParties.length;
  const status = documentVariance === 0 && (partyVariance === null || partyVariance === 0) && CA_TAX_KEYS.every(([, key]) => expected[key] === actual[key]) ? 'PASS' : 'ERROR';
  return {
    Status: status, Control: control, Message: message,
    'Expected Documents': expectedDocuments.length, 'Export Documents': actualDocuments.length, 'Document Variance': documentVariance,
    'Expected Parties': expectedParties?.length ?? 'N/A', 'Export Parties': actualParties?.length ?? 'N/A', 'Party Variance': partyVariance ?? 'N/A',
    ...Object.fromEntries(CA_TAX_KEYS.flatMap(([label, key]) => [[`Expected ${label}`, expected[key]], [`Export ${label}`, actual[key]], [`Variance ${label}`, actual[key] - expected[key]]])),
  };
}

function documentIds(rows: NormalizedGstDocument[]): string[] { return [...new Set(rows.map(row => `${row.source_entity_type}:${row.source_entity_id}`))]; }
function documentParties(rows: NormalizedGstDocument[]): string[] { return [...new Set(rows.map(row => row.party_gstin || row.party_id).filter(Boolean))]; }
function rowIds(rows: Array<{ source_entity_id: string }>): string[] { return [...new Set(rows.map(row => row.source_entity_id))]; }
function sourceCount(rows: Array<{ source_entity_id?: string; source_entity_ids?: string[] }>): number {
  return new Set(rows.flatMap(row => row.source_entity_ids ?? (row.source_entity_id ? [row.source_entity_id] : []))).size;
}

function caValidationRows(result: MonthlyGstCalculation, kind: 'gstr1' | 'purchase'): Row[] {
  const rows: Row[] = [];
  if (kind === 'gstr1') {
    const documents = result.outwardDocuments.filter(row => row.included);
    const rates = result.outwardRateRows;
    const hsn = result.outwardHsnRows;
    rows.push(caControl('REGISTER_TO_OUTWARD_NET', result.totals.outwardNet, sumAmounts(documents), result.totals.outwardNet.source_entity_ids, documentIds(documents), documentParties(documents), documentParties(documents), 'GSTR-1 register versus normalized outward net.'));
    rows.push(caControl('RATE_ROWS_TO_OUTWARD_NET', result.totals.outwardNet, sumAmounts(rates), result.totals.outwardNet.source_entity_ids, rowIds(rates), documentParties(documents), null, 'All GSTR-1 rate sections versus normalized outward net.'));
    rows.push(caControl('HSN_TO_OUTWARD_NET', result.totals.outwardNet, sumAmounts(hsn), result.totals.outwardNet.source_entity_ids, [...new Set(hsn.flatMap(row => row.source_entity_ids))], null, null, 'Outward HSN/item summary versus normalized outward net.'));
    const seriesCount = result.documentSeries.reduce((total, row) => total + row.net_issued, 0);
    const seriesControl = result.reconciliations.find(row => row.code === 'DOCUMENT_SERIES_NET_ISSUED');
    const expectedSeriesCount = seriesControl?.source_document_count ?? seriesCount;
    rows.push({ Status: seriesCount === expectedSeriesCount ? 'PASS' : 'ERROR', Control: 'DOCUMENT_SERIES_COUNT', Message: 'Document-series net issued count versus engine legal-document reconciliation, including unresolved documents.', 'Expected Documents': expectedSeriesCount, 'Export Documents': seriesCount, 'Document Variance': seriesCount - expectedSeriesCount });
  } else {
    const documents = result.inwardDocuments.filter(row => row.included);
    const notes = result.inwardNotes.filter(row => row.included);
    const purchases = documents.filter(row => !notes.some(note => note.source_entity_type === row.source_entity_type && note.source_entity_id === row.source_entity_id));
    const hsn = result.inwardHsnRows;
    rows.push(caControl('REGISTER_TO_INWARD_NET', result.totals.inwardNet, sumAmounts(documents), result.totals.inwardNet.source_entity_ids, documentIds(documents), documentParties(documents), documentParties(documents), 'Purchase register versus normalized inward net.'));
    rows.push(caControl('PURCHASES_TO_INWARD_GROSS', result.totals.inwardGross, sumAmounts(purchases), result.totals.inwardGross.source_entity_ids, documentIds(purchases), documentParties(purchases), documentParties(purchases), 'Purchase sections versus normalized inward gross.'));
    rows.push(caControl('RETURNS_TO_INWARD_NOTES', result.totals.inwardNotes, sumAmounts(notes), result.totals.inwardNotes.source_entity_ids, documentIds(notes), documentParties(notes), documentParties(notes), 'Purchase credit/debit notes versus normalized inward notes.'));
    rows.push(caControl('HSN_TO_INWARD_NET', result.totals.inwardNet, sumAmounts(hsn), result.totals.inwardNet.source_entity_ids, [...new Set(hsn.flatMap(row => row.source_entity_ids))], null, null, 'Purchase HSN/item summary versus normalized inward net.'));
    for (const head of ['IGST', 'CGST', 'SGST', 'CESS'] as const) {
      const key = `${head.toLowerCase()}_paise` as keyof GstAmounts;
      const approved = result.booksItcRows.filter(row => row.tax_head === head).reduce((total, row) => total + row.approved_paise, 0);
      const expected = result.totals.booksItc.NET_APPROVED[key];
      rows.push({ Status: approved === expected ? 'PASS' : 'ERROR', Control: `ITC_APPROVED_${head}`, Message: `Books ITC approved ${head} versus normalized approved Books ITC.`, 'Expected Approved Books ITC': expected, 'Export Approved Books ITC': approved, 'Variance Approved Books ITC': approved - expected });
    }
  }
  return [
    ...rows,
    ...result.reconciliations.map(row => ({ Status: row.status === 'PASS' ? 'PASS' : row.status === 'WARNING' ? 'WARNING' : 'ERROR', Control: `ENGINE:${row.code}`, Message: row.message })),
    ...result.issues.map(row => ({ Status: row.severity === 'BLOCKING_ERROR' ? 'ERROR' : row.severity === 'WARNING' ? 'WARNING' : 'PASS', Control: `ISSUE:${row.code}`, Message: row.message, 'Document Number': row.document_number ?? '' })),
  ];
}

function caSheet(workbook: ExcelJS.Workbook, name: string, title: string, results: MonthlyGstCalculation[], rows: Row[], documentCount?: number): void {
  const columns = [...new Set(rows.flatMap(row => Object.keys(row)))];
  if (!columns.length) columns.push('No reportable records');
  const sheet = workbook.addWorksheet(name);
  const singleMonth = results.length === 1;
  const totalTaxable = singleMonth ? paiseSum(rows, 'Taxable Value') : null;
  const totalTax = singleMonth ? ['Integrated Tax Amount', 'Central Tax Amount', 'State/UT Tax Amount', 'Cess Amount'].reduce((sum, key) => sum + paiseSum(rows, key), 0) : null;
  sheet.addRow([title]);
  sheet.mergeCells(1, 1, 1, Math.max(columns.length, 1));
  sheet.getRow(1).font = { bold: true, size: 12, color: { argb: 'FFFFFFFF' } };
  sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
  sheet.addRow(['Period', singleMonth ? results[0].period.periodKey : 'Multiple months - see Tax Period', 'GSTIN', results[0].gstinSnapshot, 'Documents', documentCount ?? rows.length, 'Taxable Value', totalTaxable === null ? 'Month-separated' : excelMoney(totalTaxable), 'Total GST', totalTax === null ? 'Month-separated' : excelMoney(totalTax)]);
  sheet.getRow(2).font = { bold: true };
  sheet.addRow(columns);
  const header = sheet.getRow(3);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF365F91' } };
  for (const row of rows) {
    const written = sheet.addRow(columns.map(column => cell(row[column], column === 'Document Date' ? 'document_date' : isCaMoneyColumn(column) ? `${column}_paise` : column, true)));
    for (let index = 1; index <= columns.length; index += 1) {
      const column = columns[index - 1];
      const current = written.getCell(index);
      if (current.value instanceof Date) current.numFmt = 'dd-mmm-yyyy';
      else if (typeof current.value === 'number') current.numFmt = column === 'Rate' || column === 'Total Quantity' ? '0.######' : MONEY_FORMAT;
      else current.numFmt = '@';
    }
  }
  sheet.views = [{ state: 'frozen', ySplit: 3 }];
  sheet.autoFilter = { from: { row: 3, column: 1 }, to: { row: Math.max(3, sheet.rowCount), column: columns.length } };
  for (let index = 1; index <= columns.length; index += 1) sheet.getColumn(index).width = Math.min(36, Math.max(14, columns[index - 1].length + 3));
}

function caSections(result: MonthlyGstCalculation, kind: 'gstr1' | 'purchase'): Array<[string, string, Row[], number?]> {
  const outwardRates = (section: string) => result.gstr1Sections.rateRows[section]?.map(caRateRow) ?? [];
  const empty: Row[] = [];
  if (kind === 'gstr1') {
    const b2bSezDeDocuments = result.outwardDocuments.filter(row => row.included
      && !result.outwardNotes.some(note => note.source_entity_type === row.source_entity_type && note.source_entity_id === row.source_entity_id)
      && ['B2B', 'SEZ_WITH_PAYMENT', 'SEZ_WITHOUT_PAYMENT', 'DEEMED_EXPORT'].includes(row.classification));
    return [
      ['GSTR1 Report', 'GSTR-1 CA Working', result.outwardDocuments.filter(row => row.included).map(row => caDocumentRow(row, 'Invoice Number')), result.totals.outwardNet.document_count],
      ['b2b,sez,de', 'B2B, SEZ and Deemed Export Customer Register (4A, 4B, 6B, 6C)', b2bSezDeDocuments.map(caOutwardCustomerRow), documentIds(b2bSezDeDocuments).length],
      ['b2cl', 'Summary For B2CL (5)', outwardRates('B2CL'), sourceCount(result.gstr1Sections.rateRows.B2CL ?? [])],
      ['b2cs', 'Summary For B2CS (7)', (result.gstr1Sections.b2csAggregates ?? []).map(row => caRateRow({ ...row, classification: 'B2CS' })), sourceCount(result.gstr1Sections.b2csAggregates ?? [])],
      ['cdnr', 'Summary For CDNR (9B)', result.outwardNotes.filter(row => row.included && row.party_gstin).map(row => caDocumentRow(row, 'Note Number')), documentIds(result.outwardNotes.filter(row => row.included && row.party_gstin)).length],
      ['cdnur', 'Summary For CDNUR (9B)', result.outwardNotes.filter(row => row.included && !row.party_gstin).map(row => caDocumentRow(row, 'Note Number')), documentIds(result.outwardNotes.filter(row => row.included && !row.party_gstin)).length],
      ['exp', 'Summary For EXP (6)', ['EXPORT_WITH_PAYMENT', 'EXPORT_WITHOUT_PAYMENT'].flatMap(outwardRates), sourceCount(['EXPORT_WITH_PAYMENT', 'EXPORT_WITHOUT_PAYMENT'].flatMap(section => result.gstr1Sections.rateRows[section] ?? []))],
      ['at', 'Summary For Advance Received (11B)', empty],
      ['atadj', 'Summary For Advance Adjusted (11B)', empty],
      ['exemp', 'Summary For Nil Rated, Exempted and Non-GST Outward Supplies (8)', result.outwardDocuments.filter(row => ['NIL_RATED', 'EXEMPT', 'NON_GST'].includes(row.classification)).map(row => caDocumentRow(row, 'Invoice Number')), documentIds(result.outwardDocuments.filter(row => ['NIL_RATED', 'EXEMPT', 'NON_GST'].includes(row.classification))).length],
      ['hsn(b2b)', 'Summary For HSN (12)', result.gstr1Sections.hsnB2b.map(caHsnRow), sourceCount(result.gstr1Sections.hsnB2b)],
      ['hsn(b2c)', 'Summary For HSN (12)', result.gstr1Sections.hsnB2c.map(caHsnRow), sourceCount(result.gstr1Sections.hsnB2c)],
      ['itemSummary', 'Summary For HSN (12)', result.outwardHsnRows.map(caHsnRow), sourceCount(result.outwardHsnRows)],
      ['docs', 'Summary of Documents Issued During the Tax Period (13)', result.documentSeries.map(row => ({ 'Document Nature': row.document_nature, Series: row.series, 'Serial From': row.serial_from, 'Serial To': row.serial_to, 'Total Issued': row.total_issued, Cancelled: row.cancelled, 'Net Issued': row.net_issued, Status: row.status }))],
      ['Validation', 'Validation / Reconciliation', caValidationRows(result, 'gstr1')],
    ];
  }
  {
    const inwardPurchases = result.inwardDocuments.filter(row => row.included && !result.inwardNotes.some(note => note.source_entity_type === row.source_entity_type && note.source_entity_id === row.source_entity_id));
    const registered = inwardPurchases.filter(row => Boolean(row.party_gstin));
    const unregistered = inwardPurchases.filter(row => !row.party_gstin);
    return [
      ['Purchase Register', 'Purchase Register / Books ITC Working', result.inwardDocuments.filter(row => row.included).map(row => caDocumentRow(row, 'Bill Number')), result.totals.inwardNet.document_count],
      ['b2b', 'Summary Of Supplies From Registered Suppliers B2B (3)', registered.map(row => caDocumentRow(row, 'Bill Number')), documentIds(registered).length],
      ['b2bur', 'Summary Of Supplies From Unregistered Suppliers B2BUR (4B)', unregistered.map(row => caDocumentRow(row, 'Bill Number')), documentIds(unregistered).length],
      ['imps', 'Summary For IMPS (4C)', empty],
      ['impg', 'Summary For IMPG (5)', empty],
      ['cdnr', 'Summary For CDNR (6C)', result.inwardNotes.filter(row => row.party_gstin).map(row => caDocumentRow(row, 'Note Number')), documentIds(result.inwardNotes.filter(row => row.party_gstin)).length],
      ['cdnur', 'Summary For CDNUR (6C)', result.inwardNotes.filter(row => !row.party_gstin).map(row => caDocumentRow(row, 'Note Number')), documentIds(result.inwardNotes.filter(row => !row.party_gstin)).length],
      ['at', 'Summary For Advance Paid Under Reverse Charge (10A)', empty],
      ['atadj', 'Summary For Adjustment of Advance Tax Paid Earlier (10B)', empty],
      ['exemp', 'Summary For Composition, Nil Rated, Exempted and Non-GST Inward Supplies (7)', result.inwardDocuments.filter(row => ['NIL_RATED', 'EXEMPT', 'NON_GST'].includes(row.classification)).map(row => caDocumentRow(row, 'Bill Number')), documentIds(result.inwardDocuments.filter(row => ['NIL_RATED', 'EXEMPT', 'NON_GST'].includes(row.classification))).length],
      ['itcr', 'Summary Input Tax Credit Reversal/Reclaim (11)', result.booksItcRows.map(row => ({ 'Tax Head': row.tax_head, Status: row.status, Category: row.category ?? '', 'Books Tax': row.books_tax_paise, Eligible: row.eligible_paise, 'Temporarily Reversed': row.temporarily_reversed_paise, 'Permanently Reversed': row.permanently_reversed_paise, Reclaimable: row.reclaimable_paise, Reclaimed: row.reclaimed_paise, 'Approved Books ITC': row.approved_paise, Reason: row.reason })), sourceCount(result.booksItcRows)],
      ['hsnsum', 'Summary For HSN (13)', result.inwardHsnRows.map(caHsnRow), sourceCount(result.inwardHsnRows)],
      ['itemSummary', 'Summary For HSN (13)', result.inwardHsnRows.map(caHsnRow), sourceCount(result.inwardHsnRows)],
      ['Validation', 'Validation / Reconciliation', caValidationRows(result, 'purchase')],
    ];
  }
}

function buildCaWorkbook(results: MonthlyGstCalculation[], kind: 'gstr1' | 'purchase'): ExcelJS.Workbook {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BusinessVault';
  const selected = selectedResults(results);
  const monthlySections = selected.map(result => caSections(result, kind));
  for (let index = 0; index < monthlySections[0].length; index += 1) {
    const [name, title] = monthlySections[0][index];
    const rows = monthlySections.flatMap((sections, resultIndex) => sections[index][2].map(row => ({ 'Tax Period': selected[resultIndex].period.periodKey, ...row })));
    const count = monthlySections.reduce((total, sections) => total + (sections[index][3] ?? sections[index][2].length), 0);
    caSheet(workbook, name, title, selected, rows, count);
  }
  return workbook;
}

// Verify presentation rows in integer paise, without classifying sources or
// replacing engine totals. Separate controls preserve the original evidence.
function exportControls(result: ExportCalculation, output: Record<SheetName, Table>): Row[] {
  const checks: Row[] = [];
  const period = result.period.periodKey;
  const data = (sheet: SheetName) => output[sheet].rows.filter(row => row['Tax Period'] === period);
  const outwardById = new Map<string, typeof result.outwardDocuments>();
  const b2csIdentities = new Set((result.gstr1Sections.documents.B2CS ?? []).map(row => `${row.source_entity_type}:${row.source_entity_id}`));
  for (const document of result.outwardDocuments) {
    const documents = outwardById.get(document.source_entity_id) ?? [];
    documents.push(document);
    outwardById.set(document.source_entity_id, documents);
  }
  const ids = (rows: Row[]) => new Set(rows.flatMap(row => {
    if (typeof row.source_entity_id === 'string') return [`${row.source_entity_type ?? ''}:${row.source_entity_id}`];
    if (!Array.isArray(row.source_entity_ids)) return [];
    return row.source_entity_ids.map(id => {
      if (!Array.isArray(row.source_entity_types)) return String(id);
      // Aggregate types are a distinct category set, not a parallel ID array.
      const matches = (outwardById.get(String(id)) ?? []).filter(document => document.included
        && (row.source_entity_types as unknown[]).includes(document.source_entity_type)
        && document.tax_period_key === period
        && b2csIdentities.has(`${document.source_entity_type}:${document.source_entity_id}`));
      const identities = new Set(matches.map(document => `${document.source_entity_type}:${document.source_entity_id}`));
      return identities.size === 1 ? [...identities][0] : `UNRESOLVED:${String(id)}`;
    });
  }));
  const total = (rows: Row[], key: string): number | null => {
    let sum = 0n;
    for (const row of rows) {
      if (row[key] == null) continue;
      money(row[key]);
      sum += BigInt(row[key] as number);
    }
    return sum <= BigInt(Number.MAX_SAFE_INTEGER) && sum >= BigInt(Number.MIN_SAFE_INTEGER) ? Number(sum) : null;
  };
  const check = (sheet: SheetName, section: string, actual: Row[], expected: Row[], keys: string[], expectedCount?: number, expectedDetails?: number) => {
    const actualIds = ids(actual), expectedIds = ids(expected);
    const row: Row = { control_origin: 'EXPORT', code: `EXPORT:${sheet}:${section}`, sheet, section, source_document_count: expectedCount ?? expectedIds.size, section_document_count: expectedCount ?? expectedIds.size, summary_document_count: expectedCount ?? null, export_document_count: actualIds.size, document_count_variance: expectedCount === undefined ? null : actualIds.size - expectedCount, export_detail_row_count: actual.length, detail_row_count: expectedDetails ?? expected.length, source_entity_ids: [...actualIds].sort(), expected_source_entity_ids: [...expectedIds].sort() };
    let error = [...actualIds].some(id => id.startsWith('UNRESOLVED:')) || expectedCount !== undefined && actualIds.size !== expectedCount || expectedDetails !== undefined && actual.length !== expectedDetails;
    if (expectedIds.size && (actualIds.size !== expectedIds.size || [...actualIds].some(id => !expectedIds.has(id)))) error = true;
    for (const key of keys) {
      const source = total(expected, key), exported = total(actual, key);
      const difference = source === null || exported === null ? null : exported - source;
      if (difference === null || !Number.isSafeInteger(difference) || difference !== 0) error = true;
      row[`source_${key}`] = source;
      row[`export_${key}`] = exported;
      row[`export_variance_${key}`] = difference !== null && Number.isSafeInteger(difference) ? difference : null;
    }
    if (expectedDetails !== undefined && actual.length === expected.length) {
      for (let index = 0; index < expected.length; index++) for (const key of keys) if ((expected[index][key] == null) !== (actual[index][key] == null)) error = true;
    }
    row.status = error ? 'ERROR' : 'PASS';
    row.message = error ? 'Export detail differs from supplied normalized control; source totals have not been repaired.' : 'Presentation rows match the supplied normalized control in integer paise.';
    checks.push(row);
  };
  const summaryRows = (amounts: GstAmounts) => [Object.fromEntries(AMOUNTS.map(key => [key, amounts[key]]))];
  for (const [sheet, summary] of [
    ['Sales Register', result.totals.outwardNet],
    ['Sales Notes', result.totals.outwardNotes],
    ['Purchase Returns', result.totals.inwardNotes],
    ['Purchase Register', result.totals.inwardNet],
  ] as const) {
    const actual = data(sheet).filter(row => row.included === true && (sheet !== 'Purchase Register' || row.row_kind === 'DOCUMENT'));
    check(sheet, 'INCLUDED', actual, summaryRows(summary), AMOUNTS, summary.document_count);
    const control = checks[checks.length - 1];
    control.expected_source_entity_ids = summary.source_entity_ids;
    const actualSourceIds = new Set(actual.map(row => row.source_entity_id));
    if (actual.length !== ids(actual).size || actualSourceIds.size !== new Set(summary.source_entity_ids).size || summary.source_entity_ids.some(id => !actualSourceIds.has(id))) control.status = 'ERROR';
    control.party_count = summary.party_count;
    control.export_party_count = new Set(actual.map(row => row.party_gstin).filter(Boolean)).size;
    control.party_count_variance = Number(control.export_party_count) - summary.party_count;
    if (control.party_count_variance !== 0) control.status = 'ERROR';
  }
  for (const [sheet, gross, notes] of [
    ['Sales Register', result.totals.outwardGross, result.outwardNotes],
    ['Purchase Register', result.totals.inwardGross, result.inwardNotes],
  ] as const) {
    const noteIds = ids(notes as unknown as Row[]);
    const actual = data(sheet).filter(row => row.included === true && (sheet !== 'Purchase Register' || row.row_kind === 'DOCUMENT') && !noteIds.has(`${row.source_entity_type}:${row.source_entity_id}`));
    check(sheet, 'GROSS', actual, summaryRows(gross), AMOUNTS, gross.document_count);
    const sourceIds = new Set(actual.map(row => row.source_entity_id));
    if (actual.length !== ids(actual).size || gross.source_entity_ids.some(id => !sourceIds.has(id))) checks[checks.length - 1].status = 'ERROR';
  }
  for (const [section, summary] of Object.entries(result.gstr1Sections.summaries)) {
    const sheet = section === 'B2B' ? 'G1 B2B' : section === 'B2CL' ? 'G1 B2CL' : section === 'B2CS' ? 'G1 B2CS' : 'G1 Other';
    const actual = data(sheet).filter(row => row.section === section);
    const aggregates = result.gstr1Sections.b2csAggregates ?? result.b2csAggregates;
    check(sheet, section, actual, summaryRows(summary), LINE_AMOUNTS, summary.document_count, section === 'B2CS' && aggregates !== undefined ? aggregates.length : summary.detail_row_count);
    const sources = result.gstr1Sections.documents[section];
    if (sources && sources.length) {
      const expectedIds = ids(sources as unknown as Row[]);
      const actualIds = ids(actual);
      if (expectedIds.size !== actualIds.size || [...expectedIds].some(id => !actualIds.has(id))) checks[checks.length - 1].status = 'ERROR';
    }
    if (sources) {
      const sourceIds = new Set(sources.map(row => `${row.source_entity_type}:${row.source_entity_id}`));
      const documents = data('Sales Register').filter(row => row.included === true && sourceIds.has(`${row.source_entity_type}:${row.source_entity_id}`));
      check('Sales Register', `G1:${section}:DOCUMENT_VALUES`, documents, summaryRows(summary), AMOUNTS, summary.document_count);
      const control = checks[checks.length - 1];
      control.party_count = summary.party_count;
      control.export_party_count = new Set(documents.map(row => row.party_gstin).filter(Boolean)).size;
      control.party_count_variance = Number(control.export_party_count) - summary.party_count;
      if (control.party_count_variance !== 0) control.status = 'ERROR';
    }
  }
  for (const sheet of ['G1 B2B', 'G1 B2CL', 'G1 B2CS', 'G1 Other'] as const) {
    const unknown = data(sheet).filter(row => !(String(row.section) in result.gstr1Sections.summaries));
    if (unknown.length) check(sheet, 'MISSING_SECTION_SUMMARY', unknown, [], LINE_AMOUNTS, 0, 0);
    if (!checks.some(row => row.sheet === sheet)) checks.push({ control_origin: 'EXPORT', code: `EXPORT:${sheet}:NOT_AVAILABLE`, sheet, section: 'NOT_AVAILABLE', status: 'WARNING', export_detail_row_count: data(sheet).length, message: 'No normalized section summary supplied. A blank sheet is not a validated nil section.' });
  }
  check('G1 Other', 'ALL_OUTWARD_RATE_HEADERS', (['G1 B2B', 'G1 B2CL', 'G1 B2CS', 'G1 Other'] as const).flatMap(data), summaryRows(result.totals.outwardNet), LINE_AMOUNTS, result.totals.outwardNet.document_count);
  for (const sheet of ['HSN B2B', 'HSN B2C'] as const) {
    const expected = result.outwardHsnRows.filter(row => sheet === 'HSN B2C' ? row.recipient_group === 'B2C' : row.recipient_group !== 'B2C');
    check(sheet, 'HSN', data(sheet), expected as unknown as Row[], LINE_AMOUNTS);
  }
  const outwardControl = result.reconciliations.find(row => row.code === 'OUTWARD_HSN_LINES');
  check('HSN B2B', 'ALL_OUTWARD_HSN_LINES', [...data('HSN B2B'), ...data('HSN B2C')], summaryRows(outwardControl?.source ?? result.totals.outwardNet), LINE_AMOUNTS, result.totals.outwardNet.document_count);
  const purchaseRows = data('Purchase Register');
  for (const kind of ['DOCUMENT', 'RATE', 'HSN']) {
    const actual = purchaseRows.filter(row => row.row_kind === kind && (kind !== 'DOCUMENT' || row.included === true));
    check('Purchase Register', kind, actual, summaryRows(result.totals.inwardNet), kind === 'DOCUMENT' ? AMOUNTS : LINE_AMOUNTS, result.totals.inwardNet.document_count);
  }
  const itc = data('Books ITC');
  for (const head of ['IGST', 'CGST', 'SGST', 'CESS'] as const) {
    const key = `${head.toLowerCase()}_paise` as keyof GstAmounts;
    const actual = itc.filter(row => row.tax_head === head);
    for (const [field, status] of [['books_tax_paise', 'TOTAL_BOOKS_TAX'], ['eligible_paise', 'ELIGIBLE_IN_BOOKS'], ['temporarily_reversed_paise', 'TEMPORARILY_REVERSED'], ['permanently_reversed_paise', 'PERMANENTLY_REVERSED'], ['reclaimable_paise', 'RECLAIMABLE'], ['reclaimed_paise', 'RECLAIMED'], ['approved_paise', 'NET_APPROVED']] as const) {
      check('Books ITC', `${head}:${field}`, actual.map(row => ({ ...row, [key]: field === 'eligible_paise' ? Number(row.eligible_paise) - Number(row.reclaimed_paise) : row[field] })), [{ [key]: result.totals.booksItc[status][key] }], [key]);
    }
    for (const status of ['UNREVIEWED', 'INELIGIBLE'] as const) check('Books ITC', `${head}:${status}`, actual.filter(row => row.status === status).map(row => ({ [key]: row.books_tax_paise })), [{ [key]: result.totals.booksItc[status][key] }], [key]);
    for (const [status, values] of Object.entries(result.totals.booksItcStatusPartitions ?? {})) {
      check('Books ITC', `${head}:PARTITION:${status}`, actual.filter(row => row.status === status).map(row => ({ ...row, [key]: row.books_tax_paise })), [{ [key]: values[key] }], [key]);
    }
  }
  const fields = data('GSTR3B Working').filter(row => row.row_kind === 'FIELD');
  for (const source of result.gstr3bSections.fields) {
    const actual = fields.filter(row => row.table_code === source.table_code && row.measure === source.measure);
    check('GSTR3B Working', `${source.table_code}:${source.measure}`, actual, [{ ...source }], ['books_derived_paise', 'gstr1_working_paise', 'approved_books_itc_paise', 'calculated_paise', 'ca_adjustment_paise', 'final_working_paise'], undefined, 1);
  }
  check('GSTR3B Working', 'INTERSTATE', data('GSTR3B Working').filter(row => row.row_kind === 'INTERSTATE'), result.gstr3bSections.interstateSupplies as unknown as Row[], AMOUNTS);
  for (const head of ['igst', 'cgst', 'sgst', 'cess']) {
    const key = `${head}_paise` as keyof GstAmounts;
    const output = fields.filter(row => ['3.1(a)', '3.1(b)', '3.1.1(i)', '3.1(d)'].includes(String(row.table_code)) && row.measure === key);
    const balance = total(output, 'calculated_paise');
    const approved = total(itc.filter(row => row.tax_head === head.toUpperCase()), 'approved_paise');
    check('GSTR3B Working', `INDICATIVE_BALANCE:${head}`, [{ [key]: balance === null || approved === null ? null : balance - approved }], [{ [key]: result.totals.indicativeWorkingBalance[key] }], [key]);
  }
  for (const [label, tableCodes, amount] of [
    ['OUTPUT_LIABILITY', ['3.1(a)', '3.1(b)', '3.1.1(i)'], result.totals.outputLiability],
    ['RCM_LIABILITY', ['3.1(d)'], result.totals.rcmLiability],
  ] as const) {
    const actual = fields.filter(row => tableCodes.some(code => code === row.table_code)).map(row => ({ [String(row.measure)]: row.calculated_paise }));
    check('GSTR3B Working', label, actual, summaryRows(amount), ['igst_paise', 'cgst_paise', 'sgst_paise', 'cess_paise']);
  }
  const series = data('Documents');
  check('Documents', 'SERIES', series, result.documentSeries as unknown as Row[], [], undefined, result.documentSeries.length);
  const seriesControl = result.reconciliations.find(row => row.code === 'DOCUMENT_SERIES_COUNT');
  const seriesCheck = checks[checks.length - 1];
  seriesCheck.source_series_count = seriesControl?.source_document_count ?? result.documentSeries.reduce((sum, row) => sum + row.total_issued, 0);
  seriesCheck.export_series_count = series.reduce((sum, row) => sum + Number(row.total_issued), 0);
  seriesCheck.series_count_variance = Number(seriesCheck.export_series_count) - Number(seriesCheck.source_series_count);
  if (seriesCheck.series_count_variance !== 0 || series.some(row => row.status === 'ERROR')) seriesCheck.status = 'ERROR';
  for (let index = 0; index < series.length; index++) {
    for (const key of ['total_issued', 'cancelled', 'net_issued']) if (series[index][key] !== result.documentSeries[index]?.[key as keyof typeof result.documentSeries[number]]) seriesCheck.status = 'ERROR';
    if (Number(series[index].total_issued) - Number(series[index].cancelled) !== series[index].net_issued) seriesCheck.status = 'ERROR';
    if (JSON.stringify(series[index].source_entity_ids) !== JSON.stringify(result.documentSeries[index]?.source_entity_ids)) seriesCheck.status = 'ERROR';
  }
  check('Issues', 'IMPACTS', data('Issues'), result.issues.map(row => Object.fromEntries(AMOUNTS.map(key => [`impact_${key}`, row.amount_impact?.[key] ?? null]))), AMOUNTS.map(key => `impact_${key}`), undefined, result.issues.length);
  for (const row of checks) if (row.status === 'ERROR') row.message = 'Export detail differs from supplied normalized control; source totals have not been repaired.';
  return checks;
}

// Tax totals come from the engine. Presentation verification sums supplied
// rows in integer paise and never replaces the normalized controls.
function tables(results: ExportCalculation[]): Record<SheetName, Table> {
  const output = {} as Record<SheetName, Table>;
  const create = (name: SheetName, columns: string[]) => { output[name] = { columns: ['Tax Period', ...columns], rows: [] }; };
  create('Overview', ['business_name', 'gstin', 'financial_year', 'filing_frequency', 'status', 'blocking_errors', 'warnings', 'disclaimer']);
  create('Monthly Summary', ['section', 'document_count', 'party_count', 'detail_row_count', 'source_entity_ids', 'tax_total_paise', ...AMOUNTS]);
  create('Sales Register', [...DOCUMENT_COLUMNS, ...SPECIAL_COLUMNS]);
  for (const name of ['G1 B2B', 'G1 B2CL', 'G1 B2CS', 'G1 Other'] as const) create(name, [...RATE_COLUMNS, 'source_entity_ids', 'source_entity_types', 'supply_type', ...SPECIAL_COLUMNS]);
  create('Sales Notes', [...DOCUMENT_COLUMNS, ...SPECIAL_COLUMNS]);
  create('HSN B2B', HSN_COLUMNS);
  create('HSN B2C', HSN_COLUMNS);
  create('Documents', ['document_nature', 'series', 'serial_from', 'serial_to', 'total_issued', 'cancelled', 'net_issued', 'gaps', 'duplicates', 'source_entity_ids', 'status']);
  create('Purchase Register', ['row_kind', ...DOCUMENT_COLUMNS, ...SPECIAL_COLUMNS, ...HSN_COLUMNS.filter(key => !DOCUMENT_COLUMNS.includes(key)), 'source_line_ids']);
  // Rate and HSN movement rows share the purchase register but are explicitly
  // tagged. Only DOCUMENT rows carry bill value and round-off.
  output['Purchase Register'].columns = [...new Set(output['Purchase Register'].columns)];
  create('Purchase Returns', [...DOCUMENT_COLUMNS, ...SPECIAL_COLUMNS]);
  create('Books ITC', ['source_entity_type', 'source_entity_id', 'ledger_entry_id', 'source_period_key', 'tax_head', 'status', 'category', 'books_tax_paise', 'unreviewed_paise', 'eligible_paise', 'temporarily_reversed_paise', 'permanently_reversed_paise', 'reclaimable_paise', 'reclaimed_paise', 'approved_paise', 'reason_code', 'reason', 'related_prior_entry_id']);
  create('GSTR3B Working', ['row_kind', 'table_code', 'measure', 'books_derived_paise', 'gstr1_working_paise', 'approved_books_itc_paise', 'calculated_paise', 'ca_adjustment_paise', 'final_working_paise', 'source_status', 'source_document_count', 'source_entity_ids', 'adjustment_ids', 'notes', 'place_of_supply', 'recipient_category', ...AMOUNTS]);
  create('Issues', ['code', 'severity', 'source_entity_type', 'source_entity_id', 'document_number', 'field', 'message', 'recommended_correction', ...AMOUNTS.map(key => `impact_${key}`)]);
  create('Reconciliation', ['control_origin', 'code', 'sheet', 'section', 'status', 'source_document_count', 'section_document_count', 'summary_document_count', 'export_document_count', 'document_count_variance', 'detail_row_count', 'export_detail_row_count', 'party_count', 'source_entity_ids', 'expected_source_entity_ids', 'message', ...AMOUNTS.flatMap(key => [`source_${key}`, `calculated_${key}`, `variance_${key}`, `export_${key}`, `export_variance_${key}`]), 'source_series_count', 'export_series_count', 'series_count_variance']);
  create('Metadata', ['business_name', 'business_id', 'gstin', 'financial_year', 'filing_frequency', 'period_start', 'next_period_start', 'generated_at', 'app_version', 'schema_version', 'rule_set_version', 'source_data_hash', 'saved_report_run_id', 'saved_status', 'calculation_status', 'export_status', 'status', 'disclaimer']);
  for (const result of results) {
    const add = (name: SheetName, row: object) => {
      // Preserve normalized type extensions (notes, UIN, amendments, advances)
      // without teaching the presentation layer their calculation semantics.
      for (const key of Object.keys(row)) if (!output[name].columns.includes(key)) output[name].columns.push(key);
      output[name].rows.push({ ...row, 'Tax Period': result.period.periodKey });
    };
    add('Overview', { business_name: result.businessName, gstin: result.gstinSnapshot, financial_year: result.period.financialYear, filing_frequency: result.period.filingFrequency, status: result.status, blocking_errors: result.issues.filter(i => i.severity === 'BLOCKING_ERROR').length, warnings: result.issues.filter(i => i.severity === 'WARNING').length, disclaimer: GST_WORKING_DISCLAIMER });
    for (const section of ['outwardGross', 'outwardNotes', 'outwardNet', 'inwardGross', 'inwardNotes', 'inwardNet', 'outputLiability', 'rcmLiability', 'indicativeWorkingBalance'] as const) {
      const values = result.totals[section];
      add('Monthly Summary', { section, ...values, ...(section === 'outputLiability' || section === 'rcmLiability' || section === 'indicativeWorkingBalance' ? { tax_total_paise: taxTotalPaise(values) } : {}) });
    }
    for (const [status, amounts] of Object.entries(result.totals.booksItc)) add('Monthly Summary', { section: `ITC:${status}`, ...amounts, tax_total_paise: taxTotalPaise(amounts) });
    for (const [status, amounts] of Object.entries(result.totals.booksItcStatusPartitions ?? {})) add('Monthly Summary', { section: `ITC_PARTITION:${status}`, ...amounts });
    for (const [section, summary] of Object.entries(result.gstr1Sections.summaries)) add('Monthly Summary', { section: `G1:${section}`, ...summary });
    for (const row of result.outwardDocuments) add('Sales Register', row);
    for (const row of result.outwardNotes) add('Sales Notes', row);
    const documents = new Map(result.outwardDocuments.map(row => [`${row.source_entity_type}:${row.source_entity_id}`, row]));
    const aggregates = result.gstr1Sections.b2csAggregates ?? result.b2csAggregates;
    for (const [section, rows] of Object.entries(result.gstr1Sections.rateRows)) {
      const sheet = section === 'B2B' ? 'G1 B2B' : section === 'B2CL' ? 'G1 B2CL' : section === 'B2CS' ? 'G1 B2CS' : 'G1 Other';
      if (section === 'B2CS' && aggregates !== undefined) continue;
      for (const row of rows) {
        const document = documents.get(`${row.source_entity_type}:${row.source_entity_id}`);
        const { total_paise: _total, round_off_paise: _round, ...detail } = { ...document, ...row };
        add(sheet, { ...detail, section });
      }
    }
    for (const row of aggregates ?? []) {
      const { total_paise: _total, round_off_paise: _round, ...detail } = row;
      add('G1 B2CS', { ...detail, section: 'B2CS' });
    }
    // Historical COMBINED and unclassified HSN rows must not disappear merely
    // because the fixed workbook has only two HSN sheets.
    for (const row of result.outwardHsnRows) {
      const { total_paise: _total, round_off_paise: _round, ...detail } = row;
      add(row.recipient_group === 'B2C' ? 'HSN B2C' : 'HSN B2B', detail);
    }
    for (const row of result.documentSeries) add('Documents', row);
    for (const row of result.inwardDocuments) add('Purchase Register', { ...row, row_kind: 'DOCUMENT' });
    for (const row of result.inwardRateRows) {
      const { total_paise: _total, round_off_paise: _round, ...detail } = row;
      add('Purchase Register', { ...detail, row_kind: 'RATE' });
    }
    for (const row of result.inwardHsnRows) {
      const { total_paise: _total, round_off_paise: _round, ...detail } = row;
      add('Purchase Register', { ...detail, row_kind: 'HSN' });
    }
    for (const row of result.inwardNotes) add('Purchase Returns', row);
    for (const row of result.booksItcRows) add('Books ITC', { ...row, unreviewed_paise: row.unreviewed_paise ?? (row.status === 'UNREVIEWED' ? row.books_tax_paise : 0) });
    for (const row of result.gstr3bSections.fields) add('GSTR3B Working', { ...row, row_kind: 'FIELD' });
    for (const row of result.gstr3bSections.interstateSupplies) add('GSTR3B Working', { ...row, row_kind: 'INTERSTATE', table_code: '3.2', notes: 'State-wise source working; not an additional liability.' });
    for (const row of result.issues) add('Issues', { ...row, ...Object.fromEntries(AMOUNTS.map(key => [`impact_${key}`, row.amount_impact?.[key] ?? null])) });
    for (const row of result.reconciliations) {
      const { source, calculated, variance, ...detail } = row;
      add('Reconciliation', { ...detail, control_origin: 'ENGINE', ...Object.fromEntries(AMOUNTS.flatMap(key => [[`source_${key}`, source[key]], [`calculated_${key}`, calculated[key]], [`variance_${key}`, variance[key]]])) });
    }
    const checks = exportControls(result, output);
    for (const row of checks) add('Reconciliation', row);
    const exportStatus = checks.some(row => row.status === 'ERROR') || result.reconciliations.some(row => row.status === 'ERROR' || Object.values(row.variance).some(value => value !== 0)) || result.issues.some(row => row.severity === 'BLOCKING_ERROR') ? 'INCOMPLETE' : result.savedStatus ?? result.status;
    output.Overview.rows[output.Overview.rows.length - 1].status = exportStatus;
    add('Metadata', { business_name: result.businessName, business_id: result.businessId, gstin: result.gstinSnapshot, financial_year: result.period.financialYear, filing_frequency: result.period.filingFrequency, period_start: result.period.periodStart, next_period_start: result.period.nextPeriodStart, generated_at: result.generatedAt, app_version: typeof __APP_VERSION__ === 'undefined' ? '0.0.0' : __APP_VERSION__, schema_version: result.schemaVersion, rule_set_version: result.ruleSetVersion, source_data_hash: result.sourceDataHash, saved_report_run_id: result.savedReportRunId ?? null, saved_status: result.savedStatus ?? null, calculation_status: result.status, export_status: exportStatus, status: exportStatus, disclaimer: GST_WORKING_DISCLAIMER });
  }
  return output;
}

function cell(value: unknown, column: string, excel: boolean): string | number | Date | null {
  if (value == null) return null;
  if (column.endsWith('_paise')) return excel ? excelMoney(value) : money(value);
  if (column === 'tax_rate_bps' || column === 'quantity_micros') {
    if (typeof value !== 'number' || !Number.isSafeInteger(value)) throw new Error('GST export requires safe fixed-point rate/quantity');
    const decimals = column === 'tax_rate_bps' ? 2 : 6;
    const scale = 10n ** BigInt(decimals), absolute = BigInt(Math.abs(value));
    const exact = `${value < 0 ? '-' : ''}${absolute / scale}.${String(absolute % scale).padStart(decimals, '0')}`;
    if (!excel) return exact;
    const numeric = Number(exact);
    if (Math.abs(value) > EXCEL_MAX_PAISE || numeric.toFixed(decimals) !== exact) throw new Error('GST XLSX rate/quantity cannot preserve fixed-point precision. Download CSV or BusinessVault working JSON for exact values.');
    return numeric;
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error('GST export contains a non-finite number');
    return value;
  }
  if (excel && column === 'generated_at') {
    const date = new Date(String(value));
    if (Number.isNaN(date.valueOf())) throw new Error('GST export contains an invalid timestamp');
    return date;
  }
  if (excel && (column.endsWith('_date') || ['period_start', 'next_period_start'].includes(column))) {
    const date = new Date(`${value}T00:00:00.000Z`);
    if (Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== value) throw new Error('GST export contains an invalid date');
    return date;
  }
  const text = typeof value === 'object' ? JSON.stringify(value) : String(value);
  // Decode the existing CSV safety helper's quoting, retaining its injection
  // guard for Excel strings without importing the DB-backed general exporter.
  if (!excel) return text;
  const safe = sanitizeCsvCell(text);
  return safe.startsWith('"') ? safe.slice(1, -1).replace(/""/g, '"') : safe;
}

async function caWorkbookResult(results: MonthlyGstCalculation[], kind: 'gstr1' | 'purchase'): Promise<{ blob: Blob; xlsxBuffer: ArrayBuffer; filename: string }> {
  const selected = selectedResults(results);
  const workbook = buildCaWorkbook(selected, kind);
  const buffer = await workbook.xlsx.writeBuffer();
  const xlsxBuffer = new Uint8Array(buffer as ArrayBuffer).slice().buffer;
  return {
    blob: new Blob([xlsxBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    xlsxBuffer,
    filename: `${kind === 'gstr1' ? 'GSTR1_Report' : 'GSTR2_Purchase_Working'}_${selected.map(result => result.period.periodKey.replace('-', '_')).join('_to_')}.xlsx`,
  };
}

export async function buildGstr1CaWorkbook(results: MonthlyGstCalculation[]): Promise<{ blob: Blob; xlsxBuffer: ArrayBuffer; filename: string }> {
  return caWorkbookResult(results, 'gstr1');
}

export async function buildPurchaseCaWorkbook(results: MonthlyGstCalculation[]): Promise<{ blob: Blob; xlsxBuffer: ArrayBuffer; filename: string }> {
  return caWorkbookResult(results, 'purchase');
}

export async function downloadGstr1CaWorkbook(results: MonthlyGstCalculation[]): Promise<void> {
  const workbook = await buildGstr1CaWorkbook(results);
  triggerDownload(workbook.blob, workbook.filename);
}

export async function downloadPurchaseCaWorkbook(results: MonthlyGstCalculation[]): Promise<void> {
  const workbook = await buildPurchaseCaWorkbook(results);
  triggerDownload(workbook.blob, workbook.filename);
}

export async function buildMonthlyGstWorkbook(results: MonthlyGstCalculation[]): Promise<{ blob: Blob; xlsxBuffer: ArrayBuffer; filename: string }> {
  const selected = selectedResults(results);
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'BusinessVault';
  for (const [name, table] of Object.entries(tables(selected))) {
    const sheet = workbook.addWorksheet(name);
    sheet.columns = table.columns.map(key => ({ header: key.endsWith('_paise') ? key.replace(/_paise$/, ' (INR)') : key === 'tax_rate_bps' ? 'Rate (%)' : key === 'quantity_micros' ? 'Quantity' : key, key, width: Math.min(40, Math.max(16, key.length + 3)) }));
    for (const row of table.rows) {
      const written = sheet.addRow(Object.fromEntries(table.columns.map(key => [key, cell(row[key], key, true)])));
      for (let index = 0; index < table.columns.length; index++) {
        const key = table.columns[index];
        const current = written.getCell(index + 1);
        current.numFmt = current.value instanceof Date ? 'dd-mmm-yyyy' : key.endsWith('_paise') ? MONEY_FORMAT : key === 'quantity_micros' ? '0.######' : key === 'tax_rate_bps' ? '0.00' : typeof current.value === 'string' ? '@' : '0';
      }
      if (row.status === 'ERROR' || row.severity === 'BLOCKING_ERROR') written.font = { color: { argb: 'FF9C0006' } };
      else if (row.status === 'WARNING' || row.severity === 'WARNING') written.font = { color: { argb: 'FF9C6500' } };
    }
    sheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
    sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
    sheet.views = [{ state: 'frozen', ySplit: 1 }];
    sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: Math.max(1, sheet.rowCount), column: table.columns.length } };
    if (name === 'Overview' || name === 'Metadata') {
      sheet.getColumn('disclaimer').width = 90;
      sheet.getColumn('disclaimer').alignment = { wrapText: true, vertical: 'top' };
      for (let index = 2; index <= sheet.rowCount; index++) sheet.getRow(index).height = 70;
    }
  }
  const buffer = await workbook.xlsx.writeBuffer();
  const xlsxBuffer = new Uint8Array(buffer as ArrayBuffer).slice().buffer;
  return { blob: new Blob([xlsxBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), xlsxBuffer, filename: filename(selected, 'xlsx') };
}

export async function downloadMonthlyGstExcel(results: MonthlyGstCalculation[]): Promise<void> {
  const result = await buildMonthlyGstWorkbook(results);
  triggerDownload(result.blob, result.filename);
}

export async function downloadMonthlyGstCsv(results: MonthlyGstCalculation[]): Promise<void> {
  const selected = selectedResults(results);
  // Validate the complete pack before starting any downloads.
  const files = Object.entries(tables(selected)).map(([name, table]) => {
    const columns = table.columns.map(key => key.endsWith('_paise') ? key.replace(/_paise$/, '_inr') : key === 'tax_rate_bps' ? 'rate_percent' : key === 'quantity_micros' ? 'quantity' : key);
    const rows = table.rows.map(row => Object.fromEntries(table.columns.map((key, index) => [columns[index], cell(row[key], key, false)])));
    return { blob: new Blob([writeCsv(rows, columns, { bom: true })], { type: 'text/csv;charset=utf-8' }), name: filename(selected, `${name.toLowerCase().replace(/ /g, '-')}.csv`) };
  });
  for (const file of files) triggerDownload(file.blob, file.name);
}

export async function downloadMonthlyGstJson(results: MonthlyGstCalculation[]): Promise<void> {
  const selected = selectedResults(results);
  const json = JSON.stringify({ schema: 'businessvault.gst-working.v1', money_unit: 'paise', disclaimer: GST_WORKING_DISCLAIMER, calculations: selected }, (key, value: unknown) => {
    if (key.endsWith('_paise') && value != null) money(value);
    if ((key.endsWith('_micros') || key.endsWith('_bps')) && value != null && (typeof value !== 'number' || !Number.isSafeInteger(value))) throw new Error('GST export requires safe fixed-point rate/quantity');
    if (typeof value === 'number' && !Number.isFinite(value)) throw new Error('GST export contains a non-finite number');
    return value;
  }, 2);
  triggerDownload(new Blob([json], { type: 'application/json' }), filename(selected, 'json'));
}

export async function downloadMonthlyGstPdf(results: MonthlyGstCalculation[]): Promise<void> {
  const selected = selectedResults(results);
  const presentation = tables(selected);
  const pdf = new jsPDF();
  const width = pdf.internal.pageSize.getWidth() - 28;
  const bottom = pdf.internal.pageSize.getHeight() - 18;
  let y = 18;
  const line = (text: string, heading = false) => {
    pdf.setFont('helvetica', heading ? 'bold' : 'normal');
    pdf.setFontSize(heading ? 12 : 9);
    for (const part of pdf.splitTextToSize(text, width) as string[]) {
      if (y > bottom) { pdf.addPage(); y = 18; }
      pdf.text(part, 14, y); y += heading ? 6 : 4.5;
    }
    y += 2;
  };
  const amounts = (label: string, values: GstAmounts) => line(`${label}: taxable INR ${money(values.taxable_paise)}; IGST ${money(values.igst_paise)}; CGST ${money(values.cgst_paise)}; SGST/UTGST ${money(values.sgst_paise)}; cess ${money(values.cess_paise)}; round-off ${money(values.round_off_paise)}; value ${money(values.total_paise)}`);
  for (let index = 0; index < selected.length; index++) {
    if (index) { pdf.addPage(); y = 18; }
    const result = selected[index];
    line('BusinessVault Monthly GST CA Summary', true);
    const saved = result as ExportCalculation;
    const exportStatus = presentation.Metadata.rows[index].export_status;
    line(`${result.businessName} | GSTIN ${result.gstinSnapshot} | ${result.period.periodKey} | ${result.period.filingFrequency} | ${exportStatus}`);
    if (saved.savedReportRunId) line(`Saved report run ${saved.savedReportRunId}; frozen source hash ${result.sourceDataHash}`);
    line(GST_WORKING_DISCLAIMER);
    line(result.gstr3bSections.disclaimer);
    for (const section of ['outwardGross', 'outwardNotes', 'outwardNet', 'inwardGross', 'inwardNotes', 'inwardNet'] as const) {
      line(`${section}: ${result.totals[section].document_count} documents`, true);
      amounts(section, result.totals[section]);
    }
    amounts('Output liability', result.totals.outputLiability);
    amounts('RCM liability', result.totals.rcmLiability);
    line('Books ITC, reversals and reclaims (subject to CA/portal reconciliation)', true);
    for (const [status, values] of Object.entries(result.totals.booksItc)) amounts(status, values);
    amounts('Indicative working balance before statutory utilization', result.totals.indicativeWorkingBalance);
    line('Draft GSTR-3B Working and CA adjustments', true);
    const amountOrUnavailable = (value: number | null) => value === null ? 'NOT_AVAILABLE' : `INR ${money(value)}`;
    for (const field of result.gstr3bSections.fields) {
      line(`${field.table_code} / ${field.measure}: books ${amountOrUnavailable(field.books_derived_paise)}; GSTR-1 ${amountOrUnavailable(field.gstr1_working_paise)}; approved Books ITC ${amountOrUnavailable(field.approved_books_itc_paise)}; calculated ${amountOrUnavailable(field.calculated_paise)}; CA adjustment ${amountOrUnavailable(field.ca_adjustment_paise)}; final working ${amountOrUnavailable(field.final_working_paise)}; ${field.source_status}; ${field.source_document_count} source documents. ${field.notes} Adjustment IDs: ${field.adjustment_ids.join(', ') || 'none'}`);
    }
    for (const row of result.gstr3bSections.interstateSupplies) amounts(`3.2 POS ${row.place_of_supply} / ${row.recipient_category}`, row);
    line(`Issues: ${result.issues.filter(issue => issue.severity === 'BLOCKING_ERROR').length} blocking errors; ${result.issues.filter(issue => issue.severity === 'WARNING').length} warnings`, true);
    for (const issue of result.issues) line(`${issue.severity} ${issue.code} | ${issue.document_number ?? issue.source_entity_id}: ${issue.message} Correction: ${issue.recommended_correction}`);
    for (const row of result.reconciliations) line(`Reconciliation ${row.code}: ${row.status}. ${row.message}`);
    for (const row of presentation.Reconciliation.rows.filter(row => row['Tax Period'] === result.period.periodKey && row.control_origin === 'EXPORT' && row.status === 'ERROR')) line(`Export reconciliation ${row.code}: ERROR. ${row.message}`);
    line(`Rules ${result.ruleSetVersion} | Schema ${result.schemaVersion} | Generated ${result.generatedAt} | Source hash ${result.sourceDataHash}`);
  }
  const pages = pdf.getNumberOfPages();
  for (let page = 1; page <= pages; page++) {
    pdf.setPage(page); pdf.setFontSize(8); pdf.setFont('helvetica', 'normal');
    pdf.text(`BusinessVault books-based working | Page ${page} of ${pages}`, 14, bottom + 10);
  }
  triggerDownload(new Blob([pdf.output('arraybuffer')], { type: 'application/pdf' }), filename(selected, 'pdf'));
}
